spring:
  datasource:
    url: jdbc:h2:file:~/.h2/security
    driverClassName: org.h2.Driver
    username: security
    password: w123456
    data:
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.H2Dialect